services:
  app:
    container_name: teste-tecnico
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - teste-tecnico

  db:
    container_name: teste-tecnico-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: teste-tecnico-db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - teste-tecnico


networks:
  teste-tecnico:
    external: true
    name: teste-tecnico

volumes:
  mysql_data:


      