services:
  app:
    container_name: teste-tecnico
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - teste-tecnico
  
  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - teste-tecnico


  db:
    container_name: teste-tecnico-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: teste-tecnico-db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - teste-tecnico


networks:
  teste-tecnico:
    external: true
    name: teste-tecnico

volumes:
  mysql_data:


      